apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ymgzSNlUWYtF6LBnFeyaN90O9KUWZeFO8SHQZtWUAnx+YbAJ,iv:rLrakLnotmi+s1hoUEmsJL0W05r0QUZXUEqVJuYhRRk=,tag:rF4KSiqWhSV7/hEoZ9SJkQ==,type:str]
    TUNNEL_TOKEN: ENC[AES256_GCM,data:qD0Gz4ohFHyGMUOlJ13YupfvgD3kDcGs2TzjoBDZPYh/S3z5QWxcfQ==,iv:iRPtqCoooDXvbopa2vf+h4gMW2RNDbe6Q27AKl1UdUQ=,tag:hiHAwMQwMr4/J5DxubLMZA==,type:str]
    credentials.json: ENC[AES256_GCM,data:kSMxrddkniuN52tvjqdCGgzNtm93F90JUWNA7kOxW/PvHF2628IDYLh5Rzb/GcMM2KVzFf2JWbQCGU/iEt5Zvnda7EgvrOSQMDa0GPB/AWhC+CzoMb3PP/emuaWo8XRZHIP/scdXlXY/EogO+L21DnV7rH78a6Fq3mVu2OhejbePfC1I1qC3cg729oP4j48C893jqE/vAYCrrpgYY0QvRVsOvWcvYPvLLTyN68Jm9Q==,iv:4SHe9lhFJ4192WjZaGeFqSprV05vh1WNjQpGz979auk=,tag:7ItCGN6K1gYDdp31spYQhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zc3ynfxvgcrmpkvznrq530p4mksk5gms93hhackd7y95p8f5uq3q2s8v9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeVZTRXh5S1dzdjlBTmFQ
            Z0R0cWpVUXczNlkwTUcwQThoc1JISEFZR2prCk13VGt3VUV5bERYZzFJMFV5WUVs
            bWRiWE1TblhGNGl4Z0FaQUJSTnhtd28KLS0tIFNNUWVXQVNTSXpXWWsvYUtsSndi
            UVBlOWdOTUNnSFlRblVtMjgxRnAzRFEKNvnlBpNnfj/9aHYAVHHOy2cCnWCBoG2D
            qRgNzIznc4r/t0C19/sxBGI17vEsIFuXkxb9ul2W4swX1rtMkEOvCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-01T20:28:48Z"
    mac: ENC[AES256_GCM,data:ZelETWA0dsiMYpYX5E1U7WXyi7k87PnLn3MZ8U/tEN8LCcOnhLZQUkNor8V9wv1MqEZX4h5jp3GOSzNysYz3ESKxLaWGP4/3T3naq4SEE+7mtxYB6G+70kH2WLqMfC1p3HZo38Ow4v/BjUBilF2kToxUFBB/GwMnsu/UKXRnEnw=,iv:260U8fjVrW+TJIktFnxKHYktBfWj3GZSh5ITe3IWkIY=,tag:08VyqY1zIs9623eR0lrTDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
