apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ZxLPRi2Y+4BKcmYKb6TLacy5AtPlxteJCKF53KBW5gZQPK+3,iv:K1lPfrjdvKxlJA2myp56rQXTbAI4gCpuWi03DDAmQfM=,tag:UOKnDqXtSVtYCWfTBGzUHA==,type:str]
    TUNNEL_TOKEN: ""
    credentials.json: ENC[AES256_GCM,data:C+aNyLKvFiaG5FBrqwTdr1SIQMNdIlYEYglEHNke6KW2V4zeLQyxo29VGgOkqbJDpy6E8lUETTZO2yXw05Hczja5NgxGI0VcKaRNAM7Zhqjbxqdn35vsuz01Ny6Vbcz0MhaAgVPv069bDDvbHsSQtXKwId5vCQpWW69mColnRfnFt0c9VWdlm0FyJ7XujLwzyVOR3bz1ildE3aS8zsdAPW3anSPoyRCJrgJYcHMVPA==,iv:OMV5YPrVCu7EDvw5HmgaSAzHU5ti3PrNSl0u2tmuPHI=,tag:seRr8T+pImvkQjGH8R+Gog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zc3ynfxvgcrmpkvznrq530p4mksk5gms93hhackd7y95p8f5uq3q2s8v9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTXdzcjM1MXRyeHN0TzZ3
            OThHNENHSkgxeGJLVWZjdXRsK2IzTm9ldlRzCkdwZ0JkemNqdUJhQW5rVFVTNER2
            NnFIVXdTeHVqbS9DSnROYVRwdFpwVjgKLS0tIGdabldnb0FRM3RwamRjaEV1SS81
            aDdnSkhYU1VZVnFaVVdPZmNzeElxdmMKFgF37xwU29d6wudg/zRNWMWBv2Kqzuhm
            zJPLlyY4GKm/isAOVfpjZCXkOrV+4wezDcUPo/KOj8y1dzKsjq1IsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-01T21:03:01Z"
    mac: ENC[AES256_GCM,data:X/M9tlcSRx/kocU3/PXcqjkPqEpzwDEGqyU0XmGFmCmcR61Amw4vXP8ACS8EJf42bzYZAXaBoM6a461do78VE9DEY6jwm45eSFGYSyaUl78w8JYB0QnjMwD6rTzXcYCbIsnZYTHLHwRJm/SUjT66Wdtq2C4+uTQBzVmD0d6YOGg=,iv:SjcWoxnHZTWsJlSg6MqbP5xwJ++nJ/DY33fZhGInxzU=,tag:HzVObRKoFoH30G4b/5Oqdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
