apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:QHQZC4s/5qXJPt7fmMq/Hqx1fUVDvG61pfsj/U5clyGDeXP/9ut2A512dqqjFWrb9yi2mBtJK9/h8/NDxI6wQJF8ecJi0p0yf9wndB2dBgamVyrYhYVXX2heIGItEA==,iv:eFwis0arg2zYa2NBU6hwtxEg4p2DVczkATTNlRRtbCg=,tag:en5kH6LZKs5wmoRpKZBIMA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:slFKq2EStsUq0JcE7KmHxA==,iv:TgI7J6+GyWPno3xKeb+YJa9cvVVHR8WEEWSmuGskJSY=,tag:+7Nq4L1t4NGQoOi+SlSiQg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:loEvx/EKAh0T6Fg/fOz7BC95T5+k72WvWcYo,iv:Gf4XHvZted7+TKuFdDAdLtfZfLsiqanr0PSKArMvepU=,tag:ZMHUe5niF3DFMDuQcJ+xZQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Xq3U2FH+d3BXEHRzH1LK7CDqWOPkAteP+2uSLi5jHrdoXchq,iv:S7dFk2SwNSKl3Q9LP/4R8rRE/K7E332kvpSW6rZDWeQ=,tag:nE6jqVZcMF10WVYk7KKaPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zc3ynfxvgcrmpkvznrq530p4mksk5gms93hhackd7y95p8f5uq3q2s8v9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bmY2c25JOEJXL2J2SFFT
            cHZONGZRNU4waDBZMGFOWHZQTVM5QkxDclg4CkxXQTlzZlZnOVRXNWk4aUlCOUNK
            WThUcndIdlMyaXlUZ3pGSFFsUnFycXMKLS0tIEx0K0pZYXpXY1lWbnhlN2w4TWoz
            NkxocWc0M3V4RWU2WVk4TGxRQUlReGcKm6J+uVyWuVSxdf+uG7RotIv0B41n1UYP
            yRl7i0AzMnrlXLmc3RapyBTHaaCw5Iv0a8K1xqB/C/Oo0P7oVOLUcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-01T20:28:48Z"
    mac: ENC[AES256_GCM,data:wgRIvfBB6ttMoWMPMSecsQ6idlq27epKFpMXBLWU4xeZWedaa7FLQRUF1KAiOu8Ft6Tjsayw7Ik1bAsjf2E/gQcEb4QAVVgPCIJTssKS8jivSnuOJVC5pnXCjRrd3svUiD6VchUyxUSOR9mgP2QqWhxhaLykgc8av6KDX142Bfk=,iv:5euid8AebiEa7mCkcdy+3IBw395pvWc0CUuSRyrOZZ4=,tag:ki0NiHl7QotRuJv7yTu3SA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
