apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:nlVgvVsOqmwqYK4AGClFS/Y0Am3II2ok,iv:sp4Di3jdut1Fx15VZhsDwjp6FrwCV/7tENKPXLSmDLI=,tag:CEeaXIRq46tgTzxpwUBVYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zc3ynfxvgcrmpkvznrq530p4mksk5gms93hhackd7y95p8f5uq3q2s8v9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodkcxWWZkS2NsOTk4Yits
            Q3FzMDRwQmp3bW5nMmR3ajJtdVRubXk5Y2pvCk90L0RIcWZrcEtMMWllcXh5Ujd0
            My94cEh1MVV0T1dZMHBJV0t0ZFdMZXcKLS0tIGxzMWNrdC9KMmJlL2ZzUytEYmV2
            VEtmaU4xcERVRjh5WDJGcWQ1MHkxYzAKCLHPdXQfNn05u373iXWQ8/ubyGemgGxf
            KTSsv7Xjgto5yPe0mcdFCHf2aKuJbjK0n9YsEYE5g6l0nR18w457pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-01T20:28:48Z"
    mac: ENC[AES256_GCM,data:ZqMpD1iJ1LF//2rpxOmVsXGzje/5b6vTXYBjl5XuLwRzIV9nPOmVjtnY+3W1LmhuTOy2xOzsx8nMyG15SYOjVaOna2xGVjFSu5VhgD8hc4d43UqRyUvPr9uQ9/zaYR4gcmliGZ3fYnmgOKF5mNyDM75XAw8guVvIyBer8h8+EUE=,iv:G5JQ4fCRz16XQco0OPtCSUEArUrQo/YcExTIUDVYSXk=,tag:h6QTXqMZS/EFsW701SDzVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
