apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:m8BS3DBqKau5IYO8rVg4g87WXLMWQ0PzIYU86kHflQzRYYBw9F4zFA==,iv:uQC68golB2L6RyZcROhPXZOLiw1zNj0X+sVNe0LOCHk=,tag:SLQAoXv1O+VZ6pJ7BNrSxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zc3ynfxvgcrmpkvznrq530p4mksk5gms93hhackd7y95p8f5uq3q2s8v9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdCtPNXp2VlE0N0d3cVVY
            bi9Rczl2cTBmejRBNTBWUzB3dWYzSERXV0d3Cm5wcjZCYXhSUHhKbUt1RHg1R3F6
            WXd2eTNFaklyUzNzUEJjenhDaVgvbWsKLS0tIDRRbitCZ0Erc2t2RDRxZFNMdEl1
            bkllTGdkVFAwWHNYbDNuL1lEL0hqdmcKNaYYodlpst3vUvXccRmGHyXnKtoT0wuD
            ELqwv1uCwNrOFXTsqQdVjLounxff0jr6zOUFs8cJbz4xApuu92p9HA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-01T19:25:29Z"
    mac: ENC[AES256_GCM,data:yx5AIjY6XtTgDMlAm3F2di3Ej2yWRxXwk6xpSzgqdjtl7JUSqX/6J4eUXikrQZ9ruA+YAOn2h6Fnf4DIlZ5pYee3kZZ5WGXs/V4Tz/3wKk83tH+ocwMwp0D/s1Tv7Nep+W4VEAieACW+6zeeie0hCNL/Cz+JsGvnDL6jAvJ6k2o=,iv:fSJpfhESP7aX4SIULrMWtjAQWZnEjRrL03+giW2Zx20=,tag:j2+JoMhT7rXR519xfvNrnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
